.PHONY: run_nameko run_a run_b run_c

all:run_nameko run_a run_b run_c

run_nameko:
	@poetry run uvicorn service_a.main:app1 --port 8001

run_a:
	@poetry run uvicorn service_a.main:app1 --port 8001

run_b:
	@poetry run uvicorn service_a.main:app2 --port 8002

run_c:
	@poetry run uvicorn service_a.main:app3 --port 8003